### ISSUE TITLE
Form validation

### ISSUE THREAD

**Issue by yannbf** [revelcw/react-hooks-helper#29]
Hello! 👋 

Thanks a lot for this library, it's quite simple and powerful!
I was wondering about the `useForm` hook. It's pretty good but I haven't seen anything about form validation. Are there any plans to include maybe another hook for that that would synergise with useForm?

**Comment by revelcw** [comment]
I'm glad you like it, but I don't have any plans for making form validation. This is just a quick little hook. Sorry. 👍

**Comment by yannbf** [comment]
Ok cool, thanks for your quick answer! Feel free to close the issue.
